# Generated by Django 5.0.3 on 2024-08-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
